[[UNRESOLVED_FN]]
id = "CODEWARE_10300"
line_contains = "UTF8StrLower"
message = "Install Codeware 1.3.0 or higher"

[[UNRESOLVED_METHOD]]
id = "CODEWARE_10300"
line_contains = "ForgetItemID"
message = "Install Codeware 1.3.0 or higher"

[[UNRESOLVED_TYPE]]
id = "CODEWARE_10300"
line_contains = "InMenuPopup"
message = "Install Codeware 1.3.0 or higher"

[[UNRESOLVED_REF]]
id = "ARCHIVEXL_10700"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.7.0 or higher"

[[UNRESOLVED_METHOD]]
id = "ARCHIVEXL_10700"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.7.0 or higher"

[[UNRESOLVED_REF]]
id = "TWEAKXL_10401"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.4.1 or higher"

[[UNRESOLVED_METHOD]]
id = "EQEX_MIX"
line_contains = "method CheckRequirements not found on EquipmentEx"
message = "Remove r6/scripts/EquipmentEx and clean install the latest version of Equipment-EX"
