[[UNRESOLVED_REF]]
id = "ARCHIVEXL_11300"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.13.0 or higher"

[[UNRESOLVED_METHOD]]
id = "ARCHIVEXL_11300"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.13.0 or higher"

[[UNRESOLVED_REF]]
id = "TWEAKXL_10805"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.8.5 or higher"

[[UNRESOLVED_FN]]
id = "CODEWARE_10900"
line_contains = "UTF8StrLower"
message = "Install Codeware 1.9.0 or higher"

[[UNRESOLVED_METHOD]]
id = "CODEWARE_10900"
line_contains = "ForgetItemID"
message = "Install Codeware 1.9.0 or higher"

[[UNRESOLVED_TYPE]]
id = "CODEWARE_10900"
line_contains = "InMenuPopup"
message = "Install Codeware 1.9.0 or higher"

[[UNRESOLVED_METHOD]]
id = "EQEX_MIX"
line_contains = "method CheckRequirements not found on EquipmentEx"
message = "Remove r6/scripts/EquipmentEx and clean install the latest version of Equipment-EX"
