[[UNRESOLVED_FN]]
id = "CODEWARE_10104"
line_contains = "UTF8StrLower"
message = "Install Codeware 1.1.4 or higher"

[[UNRESOLVED_TYPE]]
id = "CODEWARE_10104"
line_contains = "InMenuPopup"
message = "Install Codeware 1.1.4 or higher"

[[UNRESOLVED_REF]]
id = "ARCHIVEXL_10402"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.4.2 or higher"

[[UNRESOLVED_REF]]
id = "TWEAKXL_10103"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.1.3 or higher"

[[UNRESOLVED_METHOD]]
id = "EQEX_MIX"
line_contains = "method CheckRequirements not found on EquipmentEx"
message = "Remove r6/scripts/EquipmentEx and clean install the latest version of Equipment-EX"
