[[UNRESOLVED_FN]]
id = "EQEX_CODEWARE"
line_contains = "UTF8StrLower"
message = "Install Codeware 1.1.2 or higher"

[[UNRESOLVED_TYPE]]
id = "EQEX_CODEWARE"
line_contains = "InMenuPopup"
message = "Install Codeware 1.1.2 or higher"

[[UNRESOLVED_REF]]
id = "EQEX_ARCHIVEXL"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.4.2 or higher"

[[UNRESOLVED_REF]]
id = "EQEX_TWEAKXL"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.1.3 or higher"
